name: Auto Commit Random Daily

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours → 8 runs/day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "roshaniist"
          git config user.email "kumarroshan62013@gmail.com"

      - name: Random commits (0–2 per run)
        run: |
          COUNT=$((RANDOM % 3))   # 0,1,2
          echo "Will create $COUNT commits"

          for i in $(seq 1 $COUNT)
          do
            echo "Commit $i at $(date)" >> log.txt
            git add .
            git commit -m "Random update $i at $(date)" || echo "No changes"
          done

      - name: Push changes
        run: git push