name: Auto Commit Daily

on:
  push:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4   # ✅ updated

      - name: Set Git config
        run: |
          git config user.name "roshaniist"
          git config user.email "kumarroshan62013@gmail.com"

      - name: Create/Update file
        run: |
          echo "Commit at $(date)" >> log.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update log $(date)" || echo "No changes"

      - name: Push changes
        run: |
          git push